### ISSUE TITLE
Verificar si es viable la extraccion de informacion de https://es.finance.yahoo.com/

### ISSUE THREAD

**Issue by arielmeragelman** [pptscdia2021/pp12021grupo1_a2-pp12021grupo1_a2#8]
Utilizando el codigo trabajado para la bolsa de madrid intentar extraer información de https://es.finance.yahoo.com/
En caso de que no se pueda verificar si se puede obtener la informacion con la libreria beautifulsoup utilizando un codigo distinto al usado para la bolsa de madrid

**Comment by victorcba** [comment]
Tratando de realizarlo

**Comment by victorcba** [comment]
Se realizo la prueba utilizando el codigo de la bolsa de madrid. Se probo en yahoo finance [https://es.finance.yahoo.com/world-indices/](url). Se deja ejemplo
