### ISSUE TITLE
Verificar si se puede extraer información de yahoo con Selenium

### ISSUE THREAD

**Issue by arielmeragelman** [pptscdia2021/pp12021grupo1_a2-pp12021grupo1_a2#9]
En caso de que falle la extraccion en yahoo buscar la posibilidad de usar la libreria de Selenium

**Comment by victorcba** [comment]
Estoy viendo como implementarlo.

**Comment by arielmeragelman** [comment]
el proyecto se resolvio usando webscraping con beautifulsoup sobre la pagina de la bolsa de madrid y usando la api de investpy.
Se cierra el issue y solo sera requerido volver a investigar esta tecnologia si cambian los requerimientos del proyecto
